### ISSUE TITLE
[Visual bug?] Cin. Forge doesn't properly ''turn off'' when fuel runs out and no items are in the input slot

### ISSUE THREAD

**Issue by DylanGK** [paulevsGitch/BetterNether#11]
The Cin. Forge will keep the ''on'' state when it finishes smelting all that was in the input slot. This can be fixed by taking out the fuel and putting a smeltable item in there which causes it to update and turn ''off'', but yeah, visual bug so here I am reporting it.

**Comment by paulevsGitch** [comment]
Forge save fuel count, so it's probably not a bug

**Comment by Dylan4ever** [comment]
Then perhaps allign the smelting speed with the fuel duration so 16 items last for as long as 1 piece of coal burns perhaps? It is a minor annoyance.

**Comment by paulevsGitch** [comment]
They also have another speed of burning, so if furge fire indicator in GUI is active - all is ok, but if not and block is still burning it is a bug

**Comment by duely** [comment]
I've noticed this myself. Specifically, when there is nothing being processed, the forge is in the "burning" state constantly and the fuel does not wear down. However, when there is something in the processing slot but the output slot is blocked (whether by being full or being a different type of material), the fuel will continue to burn down until it burns out.

I feel as though the fuel should tick regardless of whether or not it is being used to smelt something because, at the minute, there's a significant advantage over vanilla furnaces: it's faster, and the only fuel that is actually used is the fuel used when smelting (as it pauses the rest of the time).
