### ISSUE TITLE
[Suggestion] Vanilla biome improvements

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#112]
The vanilla nether biomes, for the most part, mesh well with BN's biomes. That said, there are some improvements that could be made.

-Crimson/warped forests: some more foliage here would help the feel quite a bit. Not much, just a tad more. Some red and brown mushrooms growing on the sides of giant fungi, some moss and vines, maybe even the occasional smoker. Any of these would be welcome.

-Soul sand valley: This biome just feels barren, which I suppose is appropriate, given the theme. However, I think some patches of blue-bulbed soul grass and maybe some new mushroom would help a bit, as well as some ceiling vines.

-Basalt deltas: I feel some moss and lichen here, as well as the occasional magma flower, would be more than enough.

Unique mobs would also help of course, but I wanted to stick to simple ideas for this suggestion.

**Comment by paulevsGitch** [comment]
Thank you for suggestions. I already thought about vanilla biomes enhancements, that's why I created some sub-biomes for them. I will think more about it, as they seem unfinished for me. Somebody suggested me earlier to merge my sub-biomes for crimson and warped forests into their parent biomes.

I also recently found [this idea](https://feedback.minecraft.net/hc/en-us/community/posts/360041839552-Nether-Biome-The-Soul-Wastes-A-fungal-haunted-wastland-Includes-TONS-of-Content-Textures-and-Models). I think it is interesting (and in fact it is mostly a compilation of other mods textures and models with some editing and author's twist), but with some rework it could be added.

**Comment by theishiopian** [comment]
That's an interesting suggestion, I see what you mean about reused textures (looking at you, spoul fruit). Also, the mob that drags you down into soul sand is very similar to one of the mobs I suggested.

The soul mechanic is similar to the Intangible mod, could be pretty cool.

**Comment by quiqueck** [comment]
Moving to our Enhancement List.
