### ISSUE TITLE
Origins mod related crash

### ISSUE THREAD

**Issue by Kiktamo** [paulevsGitch/BetterNether#129]
I noticed someone else mention this on the curseforge page which led me to discover that it was the cause of my problems as well. 

Crash Log:
https://pastebin.com/KmCkWcC4

Everything loads fine if I remove the Origins mod so, here's the Origins github just in case that helps. https://github.com/apace100/origins-fabric

**Comment by paulevsGitch** [comment]
Looks like Origins adds not final tag NATURAL_STONE - [code usage](https://github.com/apace100/origins-fabric/blob/master/src/main/java/io/github/apace100/origins/mixin/AbstractBlockMixin.java#L22), [tag itself](https://github.com/apace100/origins-fabric/blob/118bd140c411b2a6cf2c8049b201d388091e19bf/src/main/java/io/github/apace100/origins/registry/ModTags.java#L14)

This tag is not initiated on game startup and when game starts it will crash as tag is not initiated (due to mods load order). All tags should be final to use them in such way.

This should be fixed at Origins side

**Comment by apace100** [comment]
Thanks for reporting and looking into this, I fixed it and the newest version of Origins should be available on CurseForge soon.
