### ISSUE TITLE
[Compatibility] Procedural recipes not working with KubeJS

### ISSUE THREAD

**Issue by DaddySpin** [paulevsGitch/BetterNether#198]
With [kubejs for fabric](https://www.curseforge.com/minecraft/mc-mods/kubejs-fabric) installed a lot of recipes just don't work anymore.

odd thing is there is no errors that i can see.

this is a list of recipes that don't work while kubejs is installed.
- Crafting Tables
- Barrels
- Furnaces
- Stools
- Roof Tiles and their stairs and slabs
- Chairs
- Bar Stools
- Ladders
- Signs
- Fire Bowls
- Planks and most stairs, slabs, fences and doors made from planks
- Quartz Glass & panes
- Obsidian Bricks stairs and slabs
- Soulsand slabs, stairs and everything else.

**Comment by paulevsGitch** [comment]
This is the result of KubeJS [mixin](https://github.com/KubeJS-Mods/KubeJS-Fabric/blob/1.16.2/src/main/java/dev/latvian/kubejs/core/mixin/RecipeManagerMixin.java) into recipe manager as it [cancels](https://github.com/KubeJS-Mods/KubeJS-Fabric/blob/1.16.2/src/main/java/dev/latvian/kubejs/core/mixin/RecipeManagerMixin.java#L27) function before other mods add their recipes. You need to add them manually if you want to use KubeJS.

The problem is not on BN side, so I will close this issue

**Comment by MaryWeeb** [comment]
Recipes should be added through datapacks, which would also solve this incompatibility.

**Comment by paulevsGitch** [comment]
Datapack recipes couldn't check component or result existence. Recipes for procedural content (like block variations), are also added procedurally. They can be added via json, but this is extremely inconvenient

**Comment by MaryWeeb** [comment]
It should be fairly easy to automate this, similar to how Blockus does it: https://github.com/Brandcraf06/Blockus/tree/1.16/src/main/resources/data/blockus/recipes

**Comment by paulevsGitch** [comment]
I think I know another way - instead hashmap overwriting I can use accessor. Recipes will stay procedural, but they will be compatible with other mods. I should try it, if it will not work I will make json recipes for compatibility

**Comment by paulevsGitch** [comment]
Fixed in 4.1.4
