### ISSUE TITLE
[Bug] No Wither skeletons in Fortress's? [1.16.3]

### ISSUE THREAD

**Issue by andylmfao** [paulevsGitch/BetterNether#201]
Hello, Me and my friend are playing on a server together. We found a nether fortress, but no Wither skeletons spawned at all. There just are none, even when using /kill @e[type=wither_skeleton] none are killed. Then i tried using /locate to find another fortress so see if it still happened. But /locate fortress doesn't work either, for some reason. It just says "Could not find that structure nearby" even when standing directly on top of one. Does anybody know a fix to either of these?

**Comment by paulevsGitch** [comment]
I think the reason is that other mobs use "monster" spawn group and overflows mob limit, I will try to fix it.

/locate command is not working for all structures - this is reported MC bug (with at least 2 reports). I fixed it for cities as players asked me for that, but not for vanilla structures. I think Mojang will fix it in 1.16.4

**Comment by andylmfao** [comment]
Okay thanks, hopefully the Wither skeleton bug is fixed soon. Currently the only other way to get skulls is to find them in the ghast cocoons, which takes forever.

**Comment by paulevsGitch** [comment]
Mob spawn fixed in 4.1.6, this should fix fortresses
