### ISSUE TITLE
Extreme load times

### ISSUE THREAD

**Issue by QazCetelic** [paulevsGitch/BetterNether#25]
Hello I added this to my modpack but I noticed a considerable load time for the Nether, after some tests these are the results:

 

**Nether Performance Test**

BOP + BetterNether
_37,73s_

BetterNether
_35,23s_

BOP
_6,08s_

None
_5,08s_

And this isn't even on a low-end machine.

**Comment by paulevsGitch** [comment]
Does any errors appears in console?

**Comment by QazCetelic** [comment]
Yes, a lot of errors. https://pastebin.com/qPjwSTF5

**Comment by paulevsGitch** [comment]
This is result of big structure generation, like Nether Cities. They are larger than single chunk and forge don't process it correctly. Same situation with some big trees. I will try to optimize this, but it is a lot of work.

At the same time generation of content in Nether is more complicated, as it goes threw all chunk height. You can make it a bit faster if you change "GlobalDensity" parameter in the config on lower values (0.1 for example instead of 1.0). Plants will become rarer and generation will go faster than before.

Also, you can disable "SecondPass" - it makes Nether more smooth, but it takes a lot of time.

Disabling "biome_wart_forest" and "biome_wart_forest_edge" will remove 80% of "cascading worldgen lag" errors, but you miss these biomes in the Nether.

**Comment by QazCetelic** [comment]
Thanks!
