### ISSUE TITLE
[Bug] Golden Vine Cannot set property class_2746

### ISSUE THREAD

**Issue by wmboeckman** [paulevsGitch/BetterNether#260]
Im creating a custom modpack, and whenever I try to enter the nether I get a server-side crash stating:

`java.lang.IllegalArgumentException: Cannot set property class_2746{name=bottom, clazz=class java.lang.Boolean, values=[true, false]} as it does not exist in Block{betternether:golden_vine}`

See server log below:
[crash-2020-12-08_14.45.04-server.txt](https://github.com/paulevsGitch/BetterNether/files/5661863/crash-2020-12-08_14.45.04-server.txt)

**Comment by wmboeckman** [comment]
I think I may have found the incompatibility here:

Im using an experimental mod from jellysquid3 called [hydrogen](https://github.com/jellysquid3/hydrogen-fabric). Its supposed to make minecraft's memory usage more efficient by modifying block state and block model objects. I believe this to be the issue, as removing it seemed to work.

Now I am wondering if ther emay be a way to make this compatible, as there must be something making the golden vine specifically not to work.

I will try to look into the golden vine code to see what temporary fix might work.

**Comment by Virtuoel** [comment]
This issue occurs because both `BlockBlackVine` and `BlockGoldenVine` blocks use `StructureVine` for generation, but each of the vines have a different<sup>[1](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/blocks/BlockBlackVine.java#L40)</sup> instance<sup>[2](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/blocks/BlockGoldenVine.java#L40)</sup> of the `BOTTOM` property, while the generator<sup>[3](https://github.com/paulevsGitch/BetterNether/blob/f996cccbb5985d19b57063b386ede1a1d146474e/src/main/java/paulevs/betternether/structures/plants/StructureVine.java#L30-L31)</sup> only uses the `BOTTOM` property of `BlockBlackVine`. One fix would be for `BlockGoldenVine` to do `public static final BooleanProperty BOTTOM = BlockBlackVine.BOTTOM;`. 
I also recommend doing something similar to vanilla's `Properties` class and keeping all your custom property instances in a single class so it's less likely to accidentally make duplicates.

**Comment by paulevsGitch** [comment]
Done, now it will probably work
