### ISSUE TITLE
Question about the Hydrogen mod.

### ISSUE THREAD

**Issue by RDKRACZ** [paulevsGitch/BetterNether#270]
I created a modpack with ~200 mods and BetterNether and BetterEnd are the only mods that don't work. Hydrogen is a too important mod to remove. What is it in Your mods and is not in others that don't play nicely with Hydrogen?

**Comment by paulevsGitch** [comment]
I don't know why, but Hydrogen changes block registering order, for some reason it add properties for blocks before blocks initialization. Block registration and initialization are the same as vanilla and other mods have, and follow fabric suggested guidelines. So, the issue is somewhere in Hydrogen, probably some wrong mixins.

What actually Hydrogen is about?

**Comment by RDKRACZ** [comment]
It reduces the memory usage of the game after startup by compacting various data structures (primarily in block state and block model objects.) ~jellysquid3. My modpack requires a whole 1GB of RAM less with this so yea.

**Comment by paulevsGitch** [comment]
So, this mod directly modifies how blocks are registered and stored in game, right? So, I couldn't do anything with this, only recommend not to use BN/BE and Hydrogen together, or wait until fix (as this is known problem)

**Comment by RDKRACZ** [comment]
Well, this sucks. BetterNether and BetterEnd are huge mods and it's pain to not be able to use them. It's still weird for me why only these two mods are affected but I understand it's something wrong with the Hydrogen.
