### ISSUE TITLE
Certain blocks take way too long to mine with the correct tools

### ISSUE THREAD

**Issue by Leo40Git** [paulevsGitch/BetterNether#304]
Yet another report from Aki's server, this time about some of the wooden blocks this mod adds.
Trying to mine said blocks with an axe results in the axe seemingly being ignored - the time taken to mine an affected block with an axe is the same as the time taken to mine that same block with your fist.

Affected blocks are: logs, ladders, trapdoors, fences.

**Comment by paulevsGitch** [comment]
This bug shouldn't exist in modern version after tag fix

**Comment by gmirmand** [comment]
Hello @paulevsGitch
Sorry to bring this topic up again, but could I get more information about this fix?
On my server, I've encountered the same issue, and the only way to fix the bug is by installing your mod. So, I assume you're fixing a bug from another mod OR a Minecraft bug, but I'm not sure which one. Thank you in advance for your help! :)
