### ISSUE TITLE
BetterNether Biomes Don't spawn Hellhounds

### ISSUE THREAD

**Issue by toErIpNid** [paulevsGitch/BetterNether#326]
When paired with the bewitchment mod, betternether biomes DO NOT spawn hellhounds whatsoever. Which is a big problem considering their drops are required to progress in the mod, and the biomes spawn with more frequency than the vanilla ones.

**Comment by MoriyaShiine** [comment]
BetterNether doesn't look like it uses the vanilla biome system, so it has no Biome.Category. Unfortunately this means that any mods that use the biome api fabric provides to add spawns to biomes and checks the category (ie Bewitchment) can't find any BetterNether biomes

**Comment by paulevsGitch** [comment]
> so it has no Biome.Category

It is wrong, [each biome has Nether category](https://github.com/paulevsGitch/BetterNether/blob/1f229eeb50a8c3d8133e333993b7e300b727ef61/src/main/java/paulevs/betternether/biomes/BiomeDefinition.java#L318)

I think the issue is much simpler - mod loading order. Bewitchment loads before BetterNether and adds entities to biomes that are already registered. The solution is also simple - add a [biome registration callback](https://github.com/paulevsGitch/BetterNether/blob/master/src/main/java/paulevs/betternether/registry/BiomesRegistry.java#L117) and add entities in it too for biomes that will be registered after Bewitchment
