### ISSUE TITLE
Better Nether Ores Mining Time increased

### ISSUE THREAD

**Issue by PuddingStick** [paulevsGitch/BetterNether#362]
Compared to 1.16.5 Better Nether, the ores take a lot longer to mine.

MODS USED ON SERVER:

Origins
Mob Origins
Extra Origins
Charm
Better Nether
Gates of Babylon
Roughly Enough Items

CLIENT SIDED MODS

Xaeros Minimap
Easier Chests

https://user-images.githubusercontent.com/86175414/122659997-67410980-d14b-11eb-8032-6c5b15ab630b.mp4

**Comment by TBiscuit1** [comment]
This happen due to the new tags on 1.17
On 1.17, they added new tags for tools effectiveness (minecraft:minable/pickaxe or minecraft:needs_iron_tool for exemple)
That means anything that doesn't have the tag will get their time multiplied since it's not the proper tool, but, since it is the proper tool, it will give the things anyway

**Comment by paulevsGitch** [comment]
As this is consequence of #364 I'm closing this
