### ISSUE TITLE
[Bug] Minability tag is missing (1.17)

### ISSUE THREAD

**Issue by TBiscuit1** [paulevsGitch/BetterNether#364]
Yes, they added tags for minability, so you can choose what can be mine with what tool and what level
So you can make dirt be mined with only a diamond axe if you want to

The thing is, every single block from better nether DOES NOT have this tag, that means, they will be strong to any tools, but efficiency enchant seems to work on every block (I have NO idea why tho)

So go look at the new minecraft:minable/X tag and minecraft:needs_X_tool, they break the mod

also, the 2 last open issues are caused by this mistake
#363 and #362 are the issues in question

**Comment by TBiscuit1** [comment]
Bonus fact, since there is no specific tool, I can mine ores with an axe, a shovel, a sword, a hoe... anything!

**Comment by vhhawk** [comment]
I think this must be what is causing the nether lapis block issue. I am unable to mine it with a vanilla tool (iron pickaxe or diamond pickaxe) and if it is mined with a "Gobber 2" mod pickaxe, it drops nothing.

**Comment by paulevsGitch** [comment]
Fixed in 5.1.1

**Comment by gmirmand** [comment]
Hello @paulevsGitch 
Sorry to bring this topic up again, but could I get more information about this fix?
On my server, I've encountered the same issue, and the only way to fix the bug is by installing your mod. So, I assume you're fixing a bug from another mod OR a Minecraft bug, but I'm not sure which one. Thank you in advance for your help! :)
