### ISSUE TITLE
[Suggestion] Netherite-Cincinasite rebalance

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#53]
Currently, CIncinasite is far superior to netherrite and is much easier to acquire. Perhaps cincinasite should be rebalanced to be around diamond level, but with less durability and lava immunity, and cincinasite-diamond should be sharper than netherite but less durable. This way cincinasite fits neatly into the "tech tree", and cincinasite-diamond is a unique sidegrade to netherrite.

**Comment by paulevsGitch** [comment]
I agree, material needs to be rebalanced. Since it was created before snapshots 1.16 it does not fit well. I think that I will change it only in 1.16 branch and in 1.15 I will leave it as it is.

**Comment by paulevsGitch** [comment]
I changed some cincinnasite armor and tool values, they should be more balanced now.

**Comment by theishiopian** [comment]
Interesting, the cincinasite is sharper, but with significantly less durability. I'd still nerf it maybe by one more damage point, but now its WAY more in balance. One interesting idea is that since cincinasite is essentially a "sidegrade" to netherrite, the cincinasite diamond tools should be crafted via smithing table as well. 

Another thing is that cincinasite ore is still relatively common. Not sure if this is an issue or not, you're probably a better judge of that.

**Comment by paulevsGitch** [comment]
I will decrease mining speed of cincinnasite-diamond tools to diamond level (it was large), and I will decrease damage to "a-bit-better-than-iron" and "a-bit-better-than-diamond" for them. I will add new recipes for smithing table, although they seem to consume one diamond instead of two, but after the rebalance it should be fine.

Cincinnasite is as common as iron (or a bit more I think), as it is also a building material. This results as the instruments of the first tier from it are approximately equivalent to iron ones, which is quite suitable for Nether in my opinion.

**Comment by theishiopian** [comment]
Yeah, I'd say first tier cincinasite should be around iron or diamond in terms of damage/speed. Also thats an interesting point about it being a building material as well, that makes balancing even more tricky.

**Comment by theishiopian** [comment]
The new values look good, but there seems to be an issue where each piece of cincinasite armor has the same armor value, specifically +6

**Comment by paulevsGitch** [comment]
This is a result of my material functions, I will replace it with individual values for each armor type.

**Comment by paulevsGitch** [comment]
I added an individual protection values for cincinnasite set, now I think it's finally balanced
