### ISSUE TITLE
[Suggestion] Ambient sound loops

### ISSUE THREAD

**Issue by theishiopian** [paulevsGitch/BetterNether#56]
Currently vanilla ambient loops only play in vanilla biomes, perhaps the vanilla loops could also be played in BN biomes?

**Comment by paulevsGitch** [comment]
I think yes, I have not watched yet new sounds, probably I will add some custom sounds for some biomes, if it is possible.

**Comment by theishiopian** [comment]
I just listened to the mushroom forest loop, i like it! However, I think that it could use a touch of reverb, along with maybe some of the additional sounds from the vanilla biomes playing occasionally (Is that what the setAdditions method is for?). Also, the loop implies a lot of insect life, so you might want to add some insect particles, kind of like The Betweenlands mod (or maybe even some new mobs though that might take longer).

**Comment by paulevsGitch** [comment]
Thanks, I will tweak it a bit (it already has reverberation, but it is not very loud). Some random sounds also will be added (this is  "additions" and "mood" made for). Mojang API provides sound randomization, so there can be many sounds for each biome (if I will be patient and skilled to do them).

**Comment by paulevsGitch** [comment]
I was thinking of adding more insects for different biomes that can make sounds. Fireflies have them, but I haven’t added their sounds yet in 1.15.

**Comment by theishiopian** [comment]
If you ever need some light sound editing done, I know a guy. Yeah, more insects would really sell the mood of the mushroom forest. Also, are the fireflies insects? I thought they were a smaller more peaceful ghast variant lol

**Comment by paulevsGitch** [comment]
Actually it's not well known, are fireflies insects or not, and have they any relations with ghasts, I prefer to think of them as insects due to the large number of their legs. By the way, I’ve already heard of their relations with ghasts, maybe I should think about something like the stages of ghasts growth. In early concepts I had ghasts hives, but they were never made, maybe I will add them.

About sounds - I am interesting, but I'm afraid of copyright issues or something like that. Actually biomes needs a lot of sounds to be alive, Mojang added nearly 96 sounds for only 5 Nether biomes. I don't think that I could reach this number, but in fact there must be 1-2 unique biome sound, other can be shared between them (like wind/dust sounds or anything like that)

**Comment by theishiopian** [comment]
Could you just call the vanilla sound events? That way you don't have to redistribute mojang assets.

**Comment by paulevsGitch** [comment]
In development snapshots code it is already done for all biomes

**Comment by paulevsGitch** [comment]
As a result I noticed, that not all sounds fits to my biomes. So I'm thinking about making my own sounds in future (not for all biomes, but for most)

**Comment by theishiopian** [comment]
Whatever works. I was just suggesting vanilla sounds as a placeholder.

**Comment by paulevsGitch** [comment]
This is also in game now
